version: '3.9'

services:

    dmm-postgres:
        container_name: dmm-postgres
        image: postgres
        restart: always
        ports:
            - 5432:5432
        networks:
            - dmm-postgres-net
        volumes:
            - dmm-postgres-data:/var/lib/postgresql/data
            - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
        env_file:
            - env/postgres.env

    dmm-rabbitmq:
        container_name: dmm-rabbitmq
        image: rabbitmq:3-management
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - dmm-rabbitmq-net
        env_file:
            - env/rabbitmq.env

    dmm-ledger:
        container_name: dmm-ledger
        build:
            dockerfile: ./docker/ledger.Dockerfile
        image: dmm/ledger
        ports:
            - 8201:8201
        depends_on:
            - dmm-postgres
            - dmm-rabbitmq
        networks:
            - dmm-postgres-net
            - dmm-rabbitmq-net
        env_file:
            - env/ledger.env

    dmm-wallet:
        container_name: dmm-wallet
        build:
            dockerfile: ./docker/wallet.Dockerfile
        image: dmm/wallet
        ports:
            - 8200:8200
        depends_on:
            - dmm-postgres
            - dmm-rabbitmq
        networks:
            - dmm-postgres-net
            - dmm-rabbitmq-net
            - dmm-pg-net
        env_file:
            - env/wallet.env

    dmm-pg:
        container_name: dmm-pg
        build:
            dockerfile: ./docker/pg.Dockerfile
        image: dmm/pg
        ports:
            - 50150:50150
        networks:
            - dmm-pg-net

networks:
    dmm-postgres-net:
        driver: bridge
    dmm-rabbitmq-net:
        driver: bridge
    dmm-pg-net:
        driver: bridge

volumes:
    dmm-postgres-data:
