version: '3.9'

services:

    dmm-wallet:
        container_name: dmm-wallet
        build:
            dockerfile: ./docker/wallet.Dockerfile
        image: dmm/wallet
        ports:
            - 8200:8200
