version: '3.9'

services:

    dmm-postgres:
        container_name: dmm-postgres
        image: postgres
        restart: always
        ports:
            - 5432:5432
        networks:
            - dmm-postgres-net
        volumes:
            - dmm-postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234

    dmm-wallet:
        container_name: dmm-wallet
        build:
            dockerfile: ./docker/wallet.Dockerfile
        image: dmm/wallet
        ports:
            - 8200:8200
        depends_on:
            - dmm-postgres
        networks:
            - dmm-postgres-net
        environment:
            - DB_HOST=dmm-postgres

networks:
    dmm-postgres-net:
        driver: bridge

volumes:
    dmm-postgres-data:
